### ISSUE TITLE
How do we run it

### ISSUE THREAD

**Issue by GitHubEmploy** [georgezouq/ai-trader#1]
How do we run it. The main file is empty.

**Comment by georgezouq** [comment]
Run the file like `python strategies/LSTM/strategy.py` directly

**Comment by GitHubEmploy** [comment]
Just wondering, does it use an API for integration to stock markets, and if so which one?

**Comment by georgezouq** [comment]
@GitHubEmploy yes, it's a backtest lib call [rqalpha](https://github.com/ricequant/rqalpha)

**Comment by GitHubEmploy** [comment]
ok, cool, so now that the problem Is solved I will close the issue
